### PR TITLE
Update cloud images for Yoga

### PR DESCRIPTION
**Pull request by priteau**
This brings compatibility with Rocky Linux 9.

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
Do we want Jammy & RL8 too? not that I can really say I'd like to keep them maintained

**Comment by priteau** [comment]
> Do we want Jammy & RL8 too? not that I can really say I'd like to keep them maintained

I added them, although maybe no one will test them.

**Review by Alex-Welsh — APPROVED** [review]
Might be worth adding a comment just to mark which images are tested and working. Otherwise LGTM

**Comment by priteau** [comment]
> Might be worth adding a comment just to mark which images are tested and working. Otherwise LGTM

Thanks. This can be in a follow-up commit.

**Pull request merged**
